### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp] Cannot turn on app

### ISSUE THREAD

**Issue by arnoudplantinga** [minvws/nl-covid19-notification-app-android#22]
Nothing happens when I press the "Turn on app" button. I'm on MIUI 1.0.7 on a Xiaomi Redmi Note 8.

Any other info I can share?

**Comment by hvisser** [comment]
There are no issues / errors about Google Play Services in that case? Is the Redmi a Google certified device with Play Store shipping? Are Covid-19 settings present in Settings -> Google on the device?

I'm not sure if you'd see anything special, but if you are able to connect your phone to a laptop and capture the output of `adb logcat` while clicking the "turn on app" button, that would be helpful.

**Comment by arnoudplantinga** [comment]
Aah, that must be the problem. I don't think this phone is Google certified.

**Comment by hvisser** [comment]
Log would still be convenient to see if there's anything we can do to report it as an error. But if it has a non-official version of Google Play Services then it's very hard to support for us unfortunately.

**Comment by arnoudplantinga** [comment]
Hope this helps! No idea where to look, but I pressed the "Turn on app" button three times.

[log2.txt](https://github.com/minvws/nl-covid19-notification-app-android/files/5095094/log2.txt)

**Comment by YellowGreen1** [comment]
G

**Comment by hvisser** [comment]
Yes, thanks! Relevant bits seem to be below, but I think this is an error that is not communicated back up to our app, which is a bit unfortunate.

```
08-19 10:39:54.505 20752 20804 E AsyncOperation: OperationException[Status{statusCode=nl.rijksoverheid.en not enabled, resolution=null}]
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at aird.b(:com.google.android.gms@202614028@20.26.14 (100400-320008519):2)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at airc.a(:com.google.android.gms@202614028@20.26.14 (100400-320008519):1)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at zvn.run(:com.google.android.gms@202614028@20.26.14 (100400-320008519):9)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at bmxs.run(:com.google.android.gms@202614028@20.26.14 (100400-320008519):2)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at sin.b(:com.google.android.gms@202614028@20.26.14 (100400-320008519):12)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at sin.run(:com.google.android.gms@202614028@20.26.14 (100400-320008519):7)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at soi.run(:com.google.android.gms@202614028@20.26.14 (100400-320008519):0)
08-19 10:39:54.505 20752 20804 E AsyncOperation: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by salar** [comment]
Just for reference: we have another report from a Xiaomi Redmi Pro 9 user with same issue.

**Comment by pflammertsma** [comment]
Can you please try to [obtain a bugreport](https://developer.android.com/studio/debug/bug-report) from any of these devices?

**Comment by salar** [comment]
The user mentioned above with a Xiaomi Redmi Pro 9 shared this screenshot with us, the device isn't Play Protect Certified.

![WhatsApp Image 2020-08-19 at 22 06 51](https://user-images.githubusercontent.com/80465/90753182-917e2c80-e2d8-11ea-8822-e5a94c404fbd.jpeg)

(cc @hvisser)
